version: "3"
services:
  php:
    build: ./php
    container_name: myapp-php
    volumes:
      - ../../projects/myapp:/www
      - ./php/log:/var/log/php

  nginx:
    image: nginx
    container_name: myapp-nginx
    ports:
      - 80:80
    volumes:
      - ../../projects/myapp:/www
      - ./nginx/log:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    build: ./db
    container_name: myapp-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: 'Asia/Tokyo'
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/log:/var/log/mysql
    ports:
      - 3306:3306
